/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(misc_utils/burst_file_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8c385079523f5e12698ff7f104202775)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/misc_utils/burst_file_sink.h>
// pydoc.h is automatically generated in the build directory
#include <burst_file_sink_pydoc.h>

void bind_burst_file_sink(py::module& m)
{

    using burst_file_sink    = ::gr::gsm::burst_file_sink;


    py::class_<burst_file_sink, gr::block, gr::basic_block,
        std::shared_ptr<burst_file_sink>>(m, "burst_file_sink", D(burst_file_sink))

        .def(py::init(&burst_file_sink::make),
           py::arg("filename"),
           D(burst_file_sink,make)
        )
        



        ;




}








